<a href="https://colab.research.google.com/github/Aswin-Kumar66/ml-practise/blob/main/nlp_with_disaster_tweets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import files
import io

uploaded = files.upload()


Saving train (4).csv to train (4).csv


In [2]:
train = pd.read_csv(io.BytesIO(uploaded['train (4).csv']))
train.head()


id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [3]:
train.isna().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [4]:
train.shape

(7613, 5)

In [6]:
train.describe(include = 'object')

keyword location                                               text
count         7552     5080                                               7613
unique         221     3341                                               7503
top     fatalities      USA  11-Year-Old Boy Charged With Manslaughter of T...
freq            45      104                                                 10

In [7]:
X = train['text']
Y = train['target']

**BAG OF WORDS**

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_bow = v.fit_transform(X)
X_bow = X_bow.toarray()
X_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [85]:

X_train_bg , X_test_bg , Y_train_bg , Y_test_bg = train_test_split(X_bow , Y , test_size = 0.2 , random_state = 15 , stratify = Y)

In [18]:
v.get_feature_names_out()[100:200]

array(['0xh758onup', '0xouv7dhwz', '0xrfvidxa2', '0yaxrjicrr',
       '0yl3yt4ylh', '0ymf6txfch', '0yo2l38ozr', '0yxbb5dzw5',
       '0yzgw9zbhr', '0z1pvjvdpf', '0zznbvfuvo', '10', '100', '1000',
       '10000', '100000', '1000s', '1008pla', '1008planet', '100bn',
       '100mb', '100nd', '100s', '101', '1017', '1023', '1028', '103',
       '105', '106', '1061thetwister', '107', '109', '10am', '10k',
       '10km', '10m', '10muey8pxj', '10news', '10pm', '10th', '10w',
       '10x', '11', '11000', '11000000', '111020', '114', '1141', '1145',
       '115', '115film', '119000', '11am', '11dvqjvxpo', '11juzhlgmt',
       '12', '1200', '12000', '120000', '1200000', '1236', '124', '125',
       '129', '12am', '12giqbvlys', '12hr', '12jst', '12m', '12mm',
       '12news', '12pm', '12th', '12u', '12v', '13', '130', '13000',
       '133', '138', '139055', '13pm', '13w8cyukkz', '14', '140', '14000',
       '14028', '141', '143', '148', '149', '14cicptkna', '14th',
       '14wh0pjj2c', '15', '150

**TF-IDF**

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()

X_tfidf = tf.fit_transform(X)
X_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [86]:

X_train_tf , X_test_tf , Y_train_tf , Y_test_tf = train_test_split(X_tfidf , Y , test_size = 0.2 , random_state = 15 , stratify = Y)

In [26]:
tf.get_feature_names_out()[5000:5100]

array(['createdunique23', 'creates', 'creating', 'creation',
       'creationmin', 'creationsbykole', 'creative', 'creativity',
       'creatures', 'credentials', 'credit', 'credited', 'credits',
       'cree', 'creek', 'creel', 'creeper', 'creepiest', 'creeping',
       'crematoria', 'crept', 'crescent', 'crest', 'crew', 'crews', 'cri',
       'cricket', 'crickets', 'cried', 'cries', 'crime', 'crimes',
       'criminal', 'criminals', 'crimsonfuckingv', 'cringes', 'crippling',
       'criscyborg', 'crisis', 'cristianinspire', 'cristiano', 'critical',
       'critically', 'criticalmedia', 'critters', 'croat', 'croatian',
       'crobscarla', 'crockery', 'crocodile', 'crooks', 'crosed', 'cross',
       'crossed', 'crosses', 'crossfit', 'crossing', 'crowd', 'crowds',
       'crowdtappers', 'crowe', 'crown', 'crowned', 'crowns',
       'crowtherjohn', 'croydon', 'croydonization', 'crozes',
       'crpo9dkw9v', 'crptotech', 'crqck', 'crucial', 'crude', 'crudes',
       'cruise', 'crumbling'

**WORD VECTORS**

In [35]:
!python -m spacy download en_core_web_sm

2023-07-07 11:08:55.195730: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.6.0/en_core_web_sm-3.6.0-py3-none-any.whl (12.8 MB)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [43]:
import spacy.cli
spacy.cli.download("en_core_web_lg")
nlp = spacy.load("en_core_web_lg")

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')


In [58]:
X_wv = X.copy()
X_wv = X_wv.apply(lambda x : nlp(x).vector)
X_wv.head()

0    [-0.965633, 0.086769275, -2.2507236, 0.4783793...
1    [-1.8681643, -1.6165241, -0.21609005, -1.76522...
2    [-2.4070368, 0.27042598, -1.3639991, 0.7013667...
3    [-1.0255101, -0.15121445, -2.2331533, 1.724021...
4    [0.08517767, -0.10672835, -1.9185519, 0.144816...
Name: text, dtype: object

In [77]:
from sklearn.model_selection import train_test_split

X_train , X_test , Y_train , Y_test = train_test_split(X_wv , Y , test_size = 0.2 , random_state = 15 , stratify = Y)

X_train

1051    [-0.95048517, -0.8859017, -0.31049064, 1.23385...
3031    [-1.3689965, 0.706491, -1.739939, 1.0094875, 5...
7294    [-1.1765876, -1.8535752, -1.2844398, -0.17182,...
6757    [-0.45859182, -0.90084034, -0.70431095, 1.6334...
2009    [-0.68448085, 1.4673467, -4.2628455, -0.540728...
                              ...                        
4622    [-0.17924042, 1.9692129, -2.0744965, -1.798893...
2182    [-0.5420507, 2.0427773, -2.3826308, -0.0081808...
498     [-2.0049832, -0.15746592, -0.26939565, 0.11025...
3000    [-0.7321983, 1.1985391, 0.66389656, -1.6111016...
7359    [-1.8200951, 0.7581784, 0.019941648, 1.4121617...
Name: text, Length: 6090, dtype: object

In [78]:
import numpy as np
X_2d_train = np.stack(X_train)
X_2d_test = np.stack(X_test)
X_2d_train

array([[-0.95048517, -0.8859017 , -0.31049064, ..., -1.4914874 ,
        -0.71248525,  0.40547904],
       [-1.3689965 ,  0.706491  , -1.739939  , ..., -0.5362331 ,
        -1.1400275 ,  0.02049389],
       [-1.1765876 , -1.8535752 , -1.2844398 , ..., -0.860594  ,
        -0.81732595, -0.8943062 ],
       ...,
       [-2.0049832 , -0.15746592, -0.26939565, ..., -0.76158005,
        -2.3264823 ,  0.01209463],
       [-0.7321983 ,  1.1985391 ,  0.66389656, ..., -1.6681353 ,
        -2.5964217 ,  2.6123574 ],
       [-1.8200951 ,  0.7581784 ,  0.01994165, ..., -0.48423418,
        -0.36995983, -0.8410075 ]], dtype=float32)

In [79]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_2d_train = scaler.fit_transform(X_2d_train)
X_2d_test = scaler.fit_transform(X_2d_test)

In [81]:
X_2d_test.shape

(1523, 300)

In [84]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

lg = LogisticRegression()
dectree = DecisionTreeClassifier()
rf = RandomForestClassifier()
nb = MultinomialNB()

models = [lg , dectree , rf , nb]

def reports(X_train , X_test , Y_train , Y_test) :
  for model in models :
    model.fit(X_train , Y_train)
    y_pred = model.predict(X_test)
    print(model)
    print(classification_report(y_pred , Y_test))


reports(X_2d_train , X_2d_test , Y_train , Y_test)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()
              precision    recall  f1-score   support

           0       0.83      0.81      0.82       897
           1       0.73      0.77      0.75       626

    accuracy                           0.79      1523
   macro avg       0.78      0.79      0.78      1523
weighted avg       0.79      0.79      0.79      1523

DecisionTreeClassifier()
              precision    recall  f1-score   support

           0       0.57      0.58      0.58       866
           1       0.44      0.44      0.44       657

    accuracy                           0.52      1523
   macro avg       0.51      0.51      0.51      1523
weighted avg       0.52      0.52      0.52      1523

RandomForestClassifier()
              precision    recall  f1-score   support

           0       0.85      0.73      0.78      1007
           1       0.59      0.74      0.65       516

    accuracy                           0.73      1523
   macro avg       0.72      0.74      0.72      1523
wei

**BAG OF WORDS**

In [87]:
reports(X_train_bg , X_test_bg , Y_train_bg, Y_test_bg)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()
              precision    recall  f1-score   support

           0       0.86      0.78      0.82       956
           1       0.68      0.79      0.73       567

    accuracy                           0.78      1523
   macro avg       0.77      0.78      0.78      1523
weighted avg       0.79      0.78      0.79      1523

DecisionTreeClassifier()
              precision    recall  f1-score   support

           0       0.81      0.75      0.78       933
           1       0.65      0.72      0.68       590

    accuracy                           0.74      1523
   macro avg       0.73      0.74      0.73      1523
weighted avg       0.75      0.74      0.74      1523

RandomForestClassifier()
              precision    recall  f1-score   support

           0       0.92      0.75      0.83      1064
           1       0.60      0.85      0.70       459

    accuracy                           0.78      1523
   macro avg       0.76      0.80      0.77      1523
wei

**TF-IDF**

In [88]:
reports(X_train_tf , X_test_tf , Y_train_tf, Y_test_tf)

LogisticRegression()
              precision    recall  f1-score   support

           0       0.90      0.78      0.83      1002
           1       0.66      0.83      0.73       521

    accuracy                           0.79      1523
   macro avg       0.78      0.80      0.78      1523
weighted avg       0.82      0.79      0.80      1523

DecisionTreeClassifier()
              precision    recall  f1-score   support

           0       0.78      0.72      0.75       946
           1       0.59      0.67      0.63       577

    accuracy                           0.70      1523
   macro avg       0.69      0.69      0.69      1523
weighted avg       0.71      0.70      0.70      1523

RandomForestClassifier()
              precision    recall  f1-score   support

           0       0.92      0.75      0.82      1072
           1       0.58      0.84      0.69       451

    accuracy                           0.77      1523
   macro avg       0.75      0.80      0.76      1523
wei

In [131]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(350 , input_shape = (300 , ) , activation = 'relu'),
    keras.layers.Dense(300, activation = 'relu'),
    keras.layers.Dense(300, activation = 'relu'),
    keras.layers.Dense(1 ,activation = 'sigmoid')


])

model.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

model.fit(X_2d_train , Y_train , epochs = 4)

Epoch 1/4
191/191 [==============================] - 2s 6ms/step - loss: 0.5926 - accuracy: 0.6831
Epoch 2/4
191/191 [==============================] - 2s 9ms/step - loss: 0.5533 - accuracy: 0.7227
Epoch 3/4
191/191 [==============================] - 2s 9ms/step - loss: 0.5275 - accuracy: 0.7471
Epoch 4/4
191/191 [==============================] - 1s 6ms/step - loss: 0.5343 - accuracy: 0.7424


In [132]:
 y_pred = model.predict(X_2d_test)
 for i in range(len(y_pred)) :
  if(y_pred[i] > 0.5) :
    y_pred[i] = 1
  else :
    y_pred[i] = 0
 print(classification_report(y_pred  , Y_test))

48/48 [==============================] - 0s 2ms/step
              precision    recall  f1-score   support

         0.0       0.67      0.83      0.74       705
         1.0       0.81      0.65      0.72       818

    accuracy                           0.73      1523
   macro avg       0.74      0.74      0.73      1523
weighted avg       0.75      0.73      0.73      1523



In [89]:
lg.fit(X_2d_train , Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [98]:
uploaded1 = files.upload()

Saving test (4).csv to test (4).csv


In [102]:
test = pd.read_csv(io.BytesIO(uploaded1['test (4).csv']))
test.head()


id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [103]:
ids = test['id']
test = test['text']
test

0                      Just happened a terrible car crash
1       Heard about #earthquake is different cities, s...
2       there is a forest fire at spot pond, geese are...
3                Apocalypse lighting. #Spokane #wildfires
4           Typhoon Soudelor kills 28 in China and Taiwan
                              ...                        
3258    EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...
3259    Storm in RI worse than last hurricane. My city...
3260    Green Line derailment in Chicago http://t.co/U...
3261    MEG issues Hazardous Weather Outlook (HWO) htt...
3262    #CityofCalgary has activated its Municipal Eme...
Name: text, Length: 3263, dtype: object

In [104]:
test = test.apply(lambda x : nlp(x).vector)
test

0       [0.13914502, 2.1093516, -3.4727995, -1.7592, 1...
1       [0.20276648, 0.45117918, -2.3882618, -0.680720...
2       [-1.3443631, 1.4944267, -3.5581467, 0.00816874...
3       [1.040925, 0.16118287, -1.705743, -0.7291729, ...
4       [-1.4714663, -3.2406561, -1.1703911, 1.7473873...
                              ...                        
3258    [0.24825662, -0.2752987, -0.44654, -0.9546411,...
3259    [-1.0159925, 0.58702713, -3.0406873, -0.402517...
3260    [-3.3830001, 0.79759836, -0.24030332, 1.280618...
3261    [-1.4187777, -2.3526988, 2.68818, 0.26845556, ...
3262    [0.6157677, 0.9711028, -0.32835814, 0.8398464,...
Name: text, Length: 3263, dtype: object

In [106]:
test = np.stack(test)
test = scaler.transform(test)

In [107]:
test

array([[0.5488093 , 0.6675531 , 0.2758789 , ..., 0.756539  , 0.7112886 ,
        0.30999056],
       [0.5556008 , 0.5228944 , 0.36542326, ..., 0.510353  , 0.69479597,
        0.55227363],
       [0.3904463 , 0.61390716, 0.26883227, ..., 0.4127968 , 0.643222  ,
        0.51283395],
       ...,
       [0.1728239 , 0.55311596, 0.5427685 , ..., 0.12922215, 0.765969  ,
        0.20888662],
       [0.38250262, 0.2782845 , 0.78455734, ..., 0.28372717, 0.8920803 ,
        0.3770371 ],
       [0.5996883 , 0.56825244, 0.53549826, ..., 0.23975477, 0.8019028 ,
        0.47761476]], dtype=float32)

In [118]:
y_pred = lg.predict(test)
y_pred = pd.DataFrame(y_pred)
ids = pd.DataFrame(ids)

finaldf = pd.concat([ids , y_pred] , axis = 1)
finaldf.to_csv('final.csv' , index = False)
files.download('final.csv')



<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [133]:
y_pred = model.predict(test)
for i in range(len(y_pred)) :
  if(y_pred[i] > 0.5) :
    y_pred[i] = 1
  else :
    y_pred[i] = 0
y_pred = pd.DataFrame(y_pred)
ids = pd.DataFrame(ids)

finaldf = pd.concat([ids , y_pred] , axis = 1)
finaldf.to_csv('final.csv' , index = False)
files.download('final.csv')



102/102 [==============================] - 0s 2ms/step


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>